// Estado Global - VORTEX 11.0

window.migrateOldTopicSchema = function(campaign) {
  if (!campaign) return;
  const numDisplay = String(campaign.number || '').padStart(2, '0');
  if (!campaign.topic || typeof campaign.topic === 'string') {
    const tText = (typeof campaign.topic === 'string' && campaign.topic) ? campaign.topic : (campaign.description || campaign.groupSubject || `Minissérie técnica de alta autoridade #${numDisplay} da InkVortex Brasil.`);
    campaign.topic = { title: campaign.title || `Minissérie #${numDisplay}`, description: tText };
  }
  const t = campaign.topic;
  const baseDesc = (t.description || t.groupSubject || campaign.description || `Minissérie técnica de alta autoridade #${numDisplay} da InkVortex Brasil.`).trim();
  
  t.title = t.title || campaign.title || `Minissérie #${numDisplay}`;
  t.description = baseDesc;
  t.editorialPromise = t.editorialPromise || baseDesc;
  t.technicalTruth = t.technicalTruth || baseDesc;
  t.why = t.why || baseDesc;
  t.angle = t.angle || 'Inovação e Alta Performance em Impressão Têxtil Especializada';
  t.centralQuestion = t.centralQuestion || t.title || 'Como essa tecnologia revoluciona a produção no mercado real?';
  t.visualDirection = t.visualDirection || baseDesc;
  campaign.gptScenes = Array.isArray(campaign.gptScenes) ? campaign.gptScenes : (Array.isArray(campaign.scenes) ? campaign.scenes : []);
  campaign.geminiScenes = Array.isArray(campaign.geminiScenes) ? campaign.geminiScenes : [];
  campaign.generatedFlow = !!campaign.generatedFlow || !!(campaign.flow && campaign.flow.prompt);
};

const AppState = {
  activeStage: 'multiverse', 
  activeSubTab: 'library', 
  libraryFilter: 'all', 
  expandedCard: null, 
  globalGptMode: 'off',
  // Provedor visual selecionado no mesmo painel do robô Gemini.
  visualRobotProvider: 'gemini',
  
  apiStatus: {
    gpt: true,
    gemini: true
  },
  
  suggestedSubjects: [],
  campaigns: [],
  selectedCampaignId: null,
  mistralKey: '', 
  isGenerating: false, 
  isGeneratingSubjects: false, 
  generatingNumbers: [], 
  generatingError: null, 
  
  init() {
    this.load();
    console.log("VORTEX 10.0 State Initialized");
  },
  
  save() {
    try {
      const data = {
        suggestedSubjects: this.suggestedSubjects,
        campaigns: this.campaigns,
        selectedCampaignId: this.selectedCampaignId,
        globalGptMode: this.globalGptMode,
        visualRobotProvider: this.visualRobotProvider,
        mistralKey: this.mistralKey,
        activeStage: this.activeStage,
        activeSubTab: this.activeSubTab,
        documentaries: this.documentaries || [],
        ctaDatabase: window.ctaDatabase || []
      };
      localStorage.setItem('vortex10_state', JSON.stringify(data));
      localStorage.setItem('vortex9_state', JSON.stringify(data));
    } catch(e) {
      console.error("Erro ao salvar estado VORTEX 10:", e);
    }
  },
  
  load() {
    try {
      const stored = localStorage.getItem('vortex10_state') || localStorage.getItem('vortex9_state') || localStorage.getItem('vortex8_state');
      if (stored) {
        const data = JSON.parse(stored);
        if (data.suggestedSubjects) this.suggestedSubjects = data.suggestedSubjects;
        if (data.campaigns) this.campaigns = data.campaigns;
        if (data.selectedCampaignId) this.selectedCampaignId = data.selectedCampaignId;
        if (data.globalGptMode) this.globalGptMode = data.globalGptMode;
        if (data.visualRobotProvider === 'chatgpt' || data.visualRobotProvider === 'gemini') this.visualRobotProvider = data.visualRobotProvider;
        if (data.mistralKey) this.mistralKey = data.mistralKey;
        if (data.activeStage) this.activeStage = data.activeStage;
        if (data.activeSubTab) this.activeSubTab = data.activeSubTab;
        if (data.documentaries) this.documentaries = data.documentaries;
        if (data.ctaDatabase) window.ctaDatabase = data.ctaDatabase;
        
        // HIGIENIZAÇÃO DE BANCO DE DADOS SOLICITADA PELO DIREITOR:
        const seenNumbers = new Set();
        this.campaigns = this.campaigns.filter(c => {
          if (c.title === 'Minissérie 3' && (!c.scenes || c.scenes.length === 0)) return false;
          if (c.topic && c.topic.description && c.topic.description.includes('Assunto inserido manualmente')) return false;
          
          // Remove duplicates generated by fast double-clicking
          if (seenNumbers.has(c.number)) return false;
          seenNumbers.add(c.number);
          
          return true;
        });

        // Garantia de migração de tópico e schema editorial completo em todas as campanhas (CRÍTICO 2)
        this.campaigns.forEach(c => {
          if (typeof window.migrateOldTopicSchema === 'function') {
            window.migrateOldTopicSchema(c);
          } else {
            const numDisplay = String(c.number || '').padStart(2, '0');
            if (!c.topic || typeof c.topic === 'string') {
              const tText = (typeof c.topic === 'string' && c.topic) ? c.topic : (c.description || c.groupSubject || `Minissérie técnica de alta autoridade #${numDisplay} da InkVortex Brasil.`);
              c.topic = { title: c.title || `Minissérie #${numDisplay}`, description: tText };
            }
          }
        });

        // LIMPEZA TOTAL DO BANCO DE ASSUNTOS (GENOMA CENTRAL V12 SOLICITADA PELO DIREITOR-GERAL):
        if (!localStorage.getItem('vortex_purge_genome_v12')) {
          this.campaigns = [];
          this.suggestedSubjects = [];
          this.selectedCampaignId = null;
          localStorage.setItem('vortex_purge_genome_v12', '1');
          console.log('🧹 Banco de dados de assuntos limpo para inicialização do Genoma Central V12.');
        }

        this.save();
      }
    } catch(e) {
      console.error("Erro ao carregar estado:", e);
    }
  },
  
  getSelectedCampaign() {
    if (!this.campaigns || this.campaigns.length === 0) return null;
    let found = this.campaigns.find(c => String(c.id) === String(this.selectedCampaignId) || String(c.number) === String(this.selectedCampaignId));
    if (!found) {
      found = this.campaigns[0];
      if (found) this.selectedCampaignId = found.id;
    }
    return found;
  }
};

window.clearAllSubjectsDatabase = function() {
  AppState.campaigns = [];
  AppState.suggestedSubjects = [];
  AppState.selectedCampaignId = null;
  AppState.save();
  if (typeof UI !== 'undefined') {
    if (typeof UI.renderWorkspace === 'function') UI.renderWorkspace();
    if (typeof UI.renderLibrary === 'function') UI.renderLibrary();
    if (typeof UI.renderIdeationGrid === 'function') UI.renderIdeationGrid();
  }
  if (typeof showToast === 'function') {
    showToast('🧹 Banco de dados de assuntos limpo com sucesso!', 'success');
  }
};
window.clearAllSubjects = window.clearAllSubjectsDatabase;

