const assert = require('assert');
const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, '..', 'gemini_current_tab_automation.js'), 'utf8');
const runStart = source.indexOf('async function runGeminiCurrentTabAutomation');
const runEnd = source.indexOf('async function runGeminiFlowCurrentTabAutomation', runStart);
const runBlock = source.slice(runStart, runEnd);
const generationLoop = source.indexOf('for (let index = 0; index < toGenerate.length; index++)', runStart);
const generationRecord = source.indexOf('recordGeminiGenerated', generationLoop);
const downloadLoop = source.indexOf('for (let index = 0; index < generatedList.length; index++)', generationLoop);
const downloadCall = source.indexOf('downloadGeminiImage({', downloadLoop);
const historyHydration = source.indexOf('await hydrateGeminiImageHistory(page, generatedList.length', generationRecord);
const insertPromptStart = source.indexOf('async function insertPrompt(page, prompt)');
const clickSendStart = source.indexOf('async function clickGeminiSend(page)', insertPromptStart);
const acceptedWaitStart = source.indexOf('async function waitForGeminiPromptAccepted', clickSendStart);
const insertPromptSource = source.slice(insertPromptStart, clickSendStart);
const clickSendSource = source.slice(clickSendStart, acceptedWaitStart);

assert(runStart >= 0 && generationLoop > runStart);
assert(runBlock.includes('await startNewGeminiChat'), 'Cada rodada normal da esteira deve abrir um novo chat Gemini.');
assert(runBlock.includes('await activateGeminiImageMode'), 'O novo chat deve ser preparado no modo Criar imagem.');
assert(!runBlock.includes('await activateGeminiComplexReasoning'), 'A esteira de 50 não pode trocar o Flash/Estendido preparado.');
assert(runBlock.includes('Novo chat Gemini preparado'), 'A esteira deve registrar a preparação do novo chat.');
assert(source.includes("element.closest('button, [role=\"button\"], [role=\"menuitem\"], [role=\"option\"], li')"), 'O clique em Criar imagem deve atingir o controle acionável, não um texto interno.');
assert(source.includes("element.getAttribute('aria-pressed')"), 'A confirmação do modo de imagem deve reconhecer aria-pressed.');
assert(source.includes("element.getAttribute('aria-selected')"), 'A confirmação do modo de imagem deve reconhecer aria-selected.');
assert(source.includes("composer.getAttribute('data-placeholder')"), 'A confirmação deve aceitar o estado semântico do compositor atual.');
assert(source.includes('for (let attempt = 0; attempt < 32; attempt++)'), 'A interface do Gemini deve receber tempo para confirmar o modo após um único clique.');
assert(!source.includes('await delay(700);\n  if (!await isActive())'), 'A validação rígida antiga de 700 ms deve permanecer retirada.');
assert(generationRecord > generationLoop, 'Cada imagem do Gemini deve ser registrada imediatamente após a geração.');
assert(downloadLoop > generationRecord, 'A fase de download deve começar somente depois da fase de geração.');
assert(downloadCall > downloadLoop, 'O download do Gemini deve permanecer dentro da segunda fase.');
assert(historyHydration > generationRecord && historyHydration < downloadLoop, 'O historico completo deve ser carregado somente entre a geracao e o download.');
assert(source.includes('currentKeys.length > previousCount'), 'Uma nova imagem deve ser confirmada pelo aumento real da lista.');
assert(source.includes('imageOrdinal: entry.imageOrdinal'), 'A identidade visual deve ser renovada pela ordem antes do download.');
assert(source.includes("element.getAttribute('aria-hidden') !== 'true'"), 'Controles ocultos nao podem manter o Gemini em falso estado ocupado.');
assert(source.includes("style.visibility !== 'hidden'"), 'Somente controles visiveis podem indicar geracao ativa.');
assert(source.includes('async function waitForGeminiComposerIdle(page, shouldCancel)'));
assert(source.includes('async function hydrateGeminiImageHistory(page, expectedCount, shouldCancel, onProgress)'));
assert(source.includes('const imageOrdinal = generated.size;'), 'A retomada deve conservar a ordem global das imagens registradas.');
assert(!source.includes('imageStillVisible'), 'A retomada do Gemini nao pode depender da hidratacao visual imediata do historico.');
assert(!insertPromptSource.includes('await delay('), 'O Gemini nao deve aguardar um tempo fixo depois de inserir o prompt.');
assert(!clickSendSource.includes('scrollIntoView'), 'O envio do Gemini nao pode deslocar a pagina para centralizar a seta.');
assert(clickSendSource.includes('}, 5000, 100);'), 'A seta habilitada deve ser verificada em intervalos curtos.');
assert(!source.includes('timeoutMs = 180000'), 'A caixa do Gemini nao pode encerrar o lote por limite fixo.');
assert(!source.includes('A caixa do Gemini nao ficou livre'), 'A antiga falha fatal da caixa deve permanecer retirada.');
assert(source.includes("const extension = path.extname(targetFileName || downloadedPath).toLowerCase() || '.png';"), 'As imagens originais do Gemini devem conservar o formato PNG.');
assert(source.includes('robotManifest.commitFile({'), 'O Gemini deve entregar o download ao manifesto unificado.');
assert(source.includes("platform: 'gemini'"), 'O robô Gemini deve usar a guia atual pela Ponte VORTEX.');
assert(!source.includes('puppeteer.launch'), 'O robô Gemini vigente não pode abrir outro navegador.');

console.log('gemini-generation-order-ok');
